### ISSUE TITLE
Building footprints for China

### ISSUE THREAD

**Issue by giswqs** [microsoft/GlobalMLBuildingFootprints#1]
Thank you for releasing the global building footprints. They are very useful. It would be nice to include the build footprints for China. Would the China data be released in the near future? Thanks for the consideration.

**Comment by giswqs** [comment]
@rbrundritt Thanks for the insights. I am aware of the [restrictions on geographic data in China](https://en.wikipedia.org/wiki/Restrictions_on_geographic_data_in_China). Since the building footprints were derived from the Maxar and Airbus imagery on Bing Maps, it would be useful to derive building footprints for China based on the existing imagery on Bing Maps. Even though the building footprint geometries for China might not line up with imagery in the future, the dataset would still be very useful and much better than nothing. The community will appreciate the dataset very much. It has been very challenging to get this kind of large-scale data for China due to government restrictions.

**Comment by bingduis** [comment]
There is already a dataset available for China though it is not vectorized and less accurate. 
Liu, Z., Tang, H., Feng, L., & Lyu, S. (2023). CBRA: The first multi-annual (2016-2021) and high-resolution (2.5 m) building rooftop area dataset in China derived with Super-resolution Segmentation from Sentinel-2 imagery (2.0) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.7861676

**Comment by frankzflyward** [comment]
> There is already a dataset available for China though it is not vectorized and less accurate. Liu, Z., Tang, H., Feng, L., & Lyu, S. (2023). CBRA: The first multi-annual (2016-2021) and high-resolution (2.5 m) building rooftop area dataset in China derived with Super-resolution Segmentation from Sentinel-2 imagery (2.0) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.7861676

Has anyone tried this yet? Is this one useful?
