### ISSUE TITLE
Wrong building height estimation for multiple buildings in US cities

### ISSUE THREAD

**Issue by LuZaiJiaoXiaL** [microsoft/GlobalMLBuildingFootprints#111]
By comparing building heights measured on Google Earth and Esri 3D building models, I found multiple estimated building heights with high confidence scores were incorrect.

Can anybody please explain whether my observation is correct?

Please check the screenshot as shown below.

![image](https://github.com/microsoft/GlobalMLBuildingFootprints/assets/35157984/5776452b-68c2-4f84-bcc2-ec9b11b8c1a6)

Best regards,

Eric

**Comment by andwoi** [comment]
Our building height estimates should be used to complement other sources, more authoritative sources. We derive heights based on aerial imagery alone so use height information where you can from 3D models, LiDAR measurements, etc. The confidence score you see here is how confident we are about a building detection not the height.
