### ISSUE TITLE
AI assisted Tasking Manager not reachable

### ISSUE THREAD

**Issue by alesarrett** [microsoft/GlobalMLBuildingFootprints#12]
The AI assisted Tasking Manager (https://tasks-assisted.hotosm.org/) mentioned in section https://github.com/microsoft/GlobalMLBuildingFootprints#will-the-data-be-used-or-made-available-in-the-larger-openstreetmap-ecosystem is not reachable.

**Comment by andwoi** [comment]
Fixed! Thanks for letting us know.
