### ISSUE TITLE
File won't open in Global Mapper

### ISSUE THREAD

**Issue by AhmetPolat43** [microsoft/GlobalMLBuildingFootprints#16]
Hello, I'm a novice in these matters. I want to open this data in the Global Mapper, then I will convert it to dxf format, but I get such an error when opening the Global Mapper. Can you help me ?How do I convert it to dxf Format in a simple way?
![image](https://user-images.githubusercontent.com/62382116/170577968-ecd5f56f-a3a7-4a58-9cb3-be619af9368a.png)

**Comment by chris** [comment]
I don't know Global Mapper, but from the error, I'd guess it can't handle a file that big (these are fairly large files). You could try [QGIS](https://qgis.org), as it handles line-delimited GeoJSON pretty well (but still somewhat depends on how much memory you have).

**Comment by AhmetPolat43** [comment]
> Hello, I'm a novice in these matters. I want to open this data in the Global Mapper, then I will convert it to dxf format, but I get such an error when opening the Global Mapper. Can you help me ?How do I convert it to dxf Format in a simple way? ![image](https://user-images.githubusercontent.com/62382116/170577968-ecd5f56f-a3a7-4a58-9cb3-be619af9368a.png)
