### ISSUE TITLE
Significant missing annotations in India

### ISSUE THREAD

**Issue by stephenjlee** [microsoft/GlobalMLBuildingFootprints#22]
Dear GlobalMLBuildingFootprints developers,

I'm finding a significant share of cells/areas with missing buildings in your India.geojsonl file. You can observe this visually in the below picture. I've read your README.md section entitled "Why are some locations missing?" and I respect those justifications. I'm still wondering if the sparsity that I am observing is expected, however. 

![image](https://user-images.githubusercontent.com/11340470/174193970-098bb8b9-c0fc-48cc-b352-8f6bf1e18831.png)

Is the sparsity observed in the above image expected?

Thank you!

Best,
Stephen

**Comment by andwoi** [comment]
Unfortunately, yes. Much of the imagery we have access to over India is older than 2014 so we did not process.
