### ISSUE TITLE
US footprint dataset vs Global MLBuilding Footprints

### ISSUE THREAD

**Issue by LjIA26** [microsoft/GlobalMLBuildingFootprints#27]
Hello! 

The US footprint dataset is separated by states, while this one is separated by countries. When I query it, it doesn't seem that I can obtain data from say California, but rather by using bounding boxes. Am I missing something ?  

code: 

items  = catalog.search(collections=["ms-buildings"], query={"msbuildings:region": {"eq": "United States"}})

Also I have just a few more questions: 
Why is it called eq? What does that stand for? 
Also, other than the building footprint polygons, do you have other information stored in this database?

**Comment by andwoi** [comment]
The data available through planetary computer is partitioned by country name and quad key. We did not create a special case for US. If you want to query for an individual state, then I suggest identifying the LOD 9 quad keys first and then performing and spatial join for best performance. 

Regarding the query language, the Planetary Computer folks are the best contact there. Here is more information on their STAC API: https://planetarycomputer.microsoft.com/docs/reference/stac/
