### ISSUE TITLE
Duplicated objects in dataset

### ISSUE THREAD

**Issue by coolmule0** [microsoft/GlobalMLBuildingFootprints#29]
I am finding cases where some buildings are repeated within the data. They tend to have one node that is different by a factor of around 10e-13, but otherwise have two entries into the database. This causes doubled-up entries in the database. 

There are numerous example of this, but one example of this occurrence is in the United Kingdom dataset, with two polygons at: 
`[(-1.1179922930346242, 53.01597035688018), (-1.1179172915810764, 53.01588208088941),  (-1.117804580503985, 53.01591673857107),  (-1.1178795819575327, 53.016005014490936), (-1.1179922930346242, 53.01597035688018)]` 
and 
`[(-1.1179922930346242, 53.01597035688018), (-1.1179172915810764, 53.015882080889405), (-1.117804580503985, 53.015916738571065), (-1.1178795819575327, 53.016005014490936), (-1.1179922930346242, 53.01597035688018)]`

**Comment by andwoi** [comment]
Thanks for flagging. We've updated the deduplication/overlap logic to fix this issue on 28 April 2023.
