### ISSUE TITLE
Finding a part of a country through the serial number

### ISSUE THREAD

**Issue by LitenSvenskStudent** [microsoft/GlobalMLBuildingFootprints#49]
Hi

I have been wondering if there is any way to know what serial number corresponds to what region in a country so one doesn't have to load all the country files to find the region one wants?

Thanks!

**Comment by andwoi** [comment]
The serial numbers are quad keys. It's a spatial indexing strategy. More info [here](https://learn.microsoft.com/en-us/bingmaps/articles/bing-maps-tile-system). There are a few libraries for converting between lat/lon and quadkey. We provide quad keys/tile IDs/tids in the [coverage map features](https://minedbuildings.blob.core.windows.net/global-buildings/buildings-coverage.geojson)
