### ISSUE TITLE
Where's the 174M footprints with height data to download?

### ISSUE THREAD

**Issue by jumpinjackie** [microsoft/GlobalMLBuildingFootprints#62]
Your latest README.md update says:

> 2023-06-05 - Combining [all building footprint releases](https://github.com/microsoft/GlobalMLBuildingFootprints#will-there-be-more-data-coming-for-other-geographies) into one distribution. Total footprints: 1.2B. Footprints with height: 174M. Updated coverage map and associated features. Other data sources will remain unchanged.

That link goes to this section of the README.md:

> Will there be more data coming for other geographies?
Maybe. This is a work in progress. Also, check out our other building releases!

>
> [US](https://github.com/microsoft/USBuildingFootprints)
> [Australia](https://github.com/microsoft/AustraliaBuildingFootprints)
> [Canada](https://github.com/microsoft/CanadianBuildingFootprints)
> [Uganda and Tanzania](https://github.com/microsoft/Uganda-Tanzania-Building-Footprints)
> [South America](https://github.com/microsoft/SouthAmericaBuildingFootprints)
> [Kenya and Nigeria](https://github.com/microsoft/KenyaNigeriaBuildingFootprints)
> [Indonesia, Malaysia, and the Philippines](https://github.com/microsoft/IdMyPhBuildingFootprints)

I download footprints for Australia and a select few US states and they are still the dumb footprint polygons without height attributes

I notice there's a Buildings with height coverage section of the README.md with this link:

> You can download the layer above as GeoJSON [here](https://minedbuildings.blob.core.windows.net/global-buildings/buildings-with-height-coverage.geojson).

That GeoJSON file is just a file of 66k coverage cells, not the actual footprints with heights.

So ... where is it?

**Comment by milos-agathon** [comment]
You can find the list of all links in this [table](https://minedbuildings.blob.core.windows.net/global-buildings/dataset-links.csv) under Url column

**Comment by andwoi** [comment]
The height values are attached to the building footprint records. Height with a -1 mean we don't have an estimate. Units are in meters.
