### ISSUE TITLE
geojson resolution and variable description

### ISSUE THREAD

**Issue by kuntalnr** [microsoft/GlobalMLBuildingFootprints#65]
Hello. Could I ask about the below link: 

https://minedbuildings.blob.core.windows.net/global-buildings/buildings-coverage.geojson

What is this data? Does it show total building area (in m2) for each square polygon?

**Comment by andwoi** [comment]
This data shows the number of buildings per quad key. The fields are quadkey, building count, and wkt. It looks like the field names are not correct. Will update

**Comment by andwoi** [comment]
i've updated the field headers. Hope that helps!
