### ISSUE TITLE
how to access building heights?

### ISSUE THREAD

**Issue by nmrosenthal** [microsoft/GlobalMLBuildingFootprints#68]
"2023-05-18 - added 77M buildings heights to the US and Western Europe. See Coverage map." --

The GeoJSON downloaded here https://github.com/microsoft/USBuildingFootprints for California does not include heights...can someone point to the repository where the updated building heights are available?

Thanks

**Comment by mjigmond** [comment]
Use the [notebook example](https://github.com/microsoft/GlobalMLBuildingFootprints/blob/main/examples/example_building_footprints.ipynb) to download the latest data. `height` is available under `properties`.

**Comment by andwoi** [comment]
@mjigmond is correct! The linked example is the best way to get the latest updates and attributes.
