### ISSUE TITLE
Mexico. Missing building polygons on extensive areas in big cities.

### ISSUE THREAD

**Issue by gtdca98** [microsoft/GlobalMLBuildingFootprints#8]
After assign geographic attributes to each geometry (state & municipal codes),  missing building polygons on extensive areas are detected.

¿would you please check if there was an issue on publishing data?, 

Thanks...

- - - - - - - -

Aguascalientes state,  194,460 building polygons

![ags01](https://user-images.githubusercontent.com/6401834/169522871-9076b9d1-563c-450e-a7e1-4becda996e0d.jpg)

looks fine.. lets zoom!!

![ags02](https://user-images.githubusercontent.com/6401834/169523004-f443d975-0d3f-4e29-b20d-948e2617d51d.jpg)

mmmm ....  panning to west side ...

![ags03](https://user-images.githubusercontent.com/6401834/169523214-4cf4adb6-58c7-49e7-80da-75ab809470f3.jpg)

google satellite image ....

![ags04](https://user-images.githubusercontent.com/6401834/169523354-51bcbce2-9aba-475f-a6d9-cb6f300afcfe.jpg)

**Comment by andwoi** [comment]
This can happen if imagery is dated prior to 2014

**Comment by gtdca98** [comment]
did you read??? =>.  https://github.com/microsoft/GlobalMLBuildingFootprints/issues?q=#:~:text=1-,Mexico%20full%20data%20process%20finds%20general%20poor%20detection.%2043%25%20of%20urban%20blocks%20has%20no%20buildingFootprints.,-%2317%20opened%20on 

In your answer you imply   :  "Mexico buit 43% of buildings in the last 8 years!!!"
